version: "3.8"

services:
  milvus:
    image: milvusdb/milvus:v2.2.11
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/var/lib/milvus/etcd/etcd.conf
      - MINIO_DATA_PATH=/var/lib/milvus/minio
      - MILVUS_COMMON_STORAGETYPE=local
      - MILVUS_COMMON_STORAGEPATH=/var/lib/milvus
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1.0
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  milvus_data: 